### ISSUE TITLE
not installable via pypi

### ISSUE THREAD

**Issue by imacdonald** [dufferzafar/tagtool#4]
tagtool 1.0.7 isn't installable via pypi as Readme.md is missing from the tar.gz file. Adding the file, available from github, fixes this problem.

**Comment by mzfr** [comment]
@dufferzafar I am facing the same issue

**Comment by mzfr** [comment]
@imacdonald This can be fixed if you install it using [pipsi](https://github.com/mitsuhiko/pipsi) to do so run `pipsi install git+https://github.com/dufferzafar/tagtool#egg=tagtool                                                                                 `
